import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  docs: [
    {
      type: 'html',
      value: '<span class="sidebar-heading first">Welcome</span>',
    },
    'introduction',
    'getting-started',

    {
      type: 'html',
      value: '<span class="sidebar-heading">Learn</span>',
    },
    {
      type: 'category',
      label: 'Architecture',
      link: {
        type: 'doc',
        id: 'architecture/README',
      },
      items: [
        'architecture/dkim-verification',
        'architecture/zk-proofs',
        'architecture/on-chain',
        'architecture/security-considerations',
      ],
    },
    {
      type: 'html',
      value: '<span class="sidebar-heading">SDK</span>',
    },
    'zk-email-sdk/README',
    'zk-email-sdk/running-the-example',
    'zk-email-sdk/creating-a-new-pattern',
    // {
    //   type: 'html',
    //   value: '<span class="sidebar-heading">SDK v2</span>',
    // },
    // 'zk-email-sdk/overview',
    // 'zk-email-sdk/setup',
    // 'zk-email-sdk/blueprint',
    {
      type: 'html',
      value: '<span class="sidebar-heading">ZK Email Verifier</span>',
    },
    'zk-email-verifier/README',
    'zk-email-verifier/setup',
    'zk-email-verifier/usage-guide',
    {
      type: 'category',
      label: 'Packages',
      link: {
        type: 'doc',
        id: 'zk-email-verifier/packages/README',
      },
      items: [
        'zk-email-verifier/packages/zk-email-circuits',
        'zk-email-verifier/packages/zk-email-helpers',
        'zk-email-verifier/packages/zk-email-contracts'
      ],
    },
    {
      type: 'html',
      value: '<span class="sidebar-heading">Email Wallet</span>',
    },
    'email-wallet/README',
    'email-wallet/circuit-architecture',
    'email-wallet/contract-architecture',
    'email-wallet/relayer-infrastructure',
    'email-wallet/email-wallet-extensions-sdk',
    'email-wallet/deployed-contract-addresses',
    {
      type: 'html',
      value: '<span class="sidebar-heading">Account Recovery</span>',
    },
    'account-recovery/README',
    // {
    //   type: 'category',
    //   label: 'Quickstart',
    //   link: {
    //     type: 'doc',
    //     id: 'account-recovery/quickstart/README',
    //   },
    //   items: [
    //     'account-recovery/quickstart/existing-modules',
    //     'account-recovery/quickstart/ether-email-auth',
    //   ],
    // },
    'account-recovery/architecture',
    'account-recovery/setup',
    'account-recovery/relayer-api/README',
    'account-recovery/deployed-contracts',

    {
      type: 'html',
      value: '<span class="sidebar-heading">Email Transaction Auth</span>',
    },
    'email-tx-builder/README',
    'email-tx-builder/quickstart',
    'email-tx-builder/setup',
    {
      type: 'category',
      label: 'Architecture',
      link: {
        type: 'doc',
        id: 'email-tx-builder/architecture/README'
      },
      items: [
        'email-tx-builder/architecture/concepts',
        'email-tx-builder/architecture/package-components',
        'email-tx-builder/architecture/generic-relayer',
        'email-tx-builder/architecture/command-templates',
      ],
    },
    'email-tx-builder/api-reference',
    {
      type: 'category',
      label: 'Ether Email Auth SDK',
      link: {
        type: 'doc',
        id: 'email-tx-builder/email-tx-auth/README'
      },
      items: [
      ],
    },

    {
      type: 'html',
      value: '<span class="sidebar-heading">Additional Resources</span>',
    },
    {
      type: 'link',
      label: 'Projects using ZK Email',
      href: 'https://prove.email/projects',
    },
    'login-with-zk-email-oauth-api',
    'audits',
    'zk-regex',
    'frequently-asked-questions',
    'contributing',
  ],
};

export default sidebars;
