import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  docs: [
    {
      type: 'html',
      value: '<span class="sidebar-heading first">Welcome</span>',
    },
    'intro',
    {
      type: 'html',
      value: '<span class="sidebar-heading">SDK</span>',
    },
    {
      type: 'category',
      label: 'ZK Email SDK',
      link: {
        type: 'doc',
        id: 'zk-email-sdk/README',
      },
      items: [
        'zk-email-sdk/running-the-example',
        'zk-email-sdk/creating-a-new-pattern',
        'zk-email-sdk/using-the-sdk',
      ],
    },
    {
      type: 'html',
      value: '<span class="sidebar-heading">ZK Email Verifier</span>',
    },
    {
      type: 'category',
      label: 'ZK-Email-Verifier',
      link: {
        type: 'doc',
        id: 'zk-email-verifier/README',
      },
      items: [
        'zk-email-verifier/installation',
        'zk-email-verifier/packages-components',
        'zk-email-verifier/usage-guide',
      ],
    },
    {
      type: 'html',
      value: '<span class="sidebar-heading">Email Wallet</span>',
    },
    {
      type: 'category',
      label: 'Email Wallet',
      link: {
        type: 'doc',
        id: 'email-wallet/README',
      },
      items: [
        'email-wallet/api-documentation',
        'email-wallet/circuit-architecture',
        'email-wallet/contract-architecture',
        'email-wallet/relayer-infrastructure',
        'email-wallet/email-wallet-extensions-sdk',
        'email-wallet/deployed-contract-addresses',
      ],
    },
    {
      type: 'html',
      value: '<span class="sidebar-heading">Account Recovery</span>',
    },
    {
      type: 'category',
      label: 'Account Recovery',
      link: {
        type: 'doc',
        id: 'account-recovery/README',
      },
      items: [
        'account-recovery/email-controlled-smart-contracts',
        'account-recovery/novel-concepts',
        'account-recovery/package-components',
        'account-recovery/getting-started',
        {
          type: 'category',
          label: 'Relayer API',
          link: {
            type: 'doc',
            id: 'account-recovery/relayer-api/README'
          },
          items: [
            'account-recovery/relayer-api/echo-endpoint',
            'account-recovery/relayer-api/request-status',
            'account-recovery/relayer-api/acceptance-request',
            'account-recovery/relayer-api/recovery-request',
            'account-recovery/relayer-api/complete-recovery-request',
            'account-recovery/relayer-api/get-account-salt',
          ],
        },
        'account-recovery/deployed-contracts',
      ],
    },
    {
      type: 'html',
      value: '<span class="sidebar-heading">Additional Resources</span>',
    },
    'login-with-zk-email-oauth-api',
    'audits',
    'zk-regex',
    'frequently-asked-questions',
    'contributing',
  ],
};

export default sidebars;
